# Generated by Django 6.0.4 on 2026-05-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('milliliter', 'Ml'), ('Liter', 'L')], max_length=255)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
